//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.07 at 06:48:08 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://trng.xsd/customer/0.0.1")
package trng.xsd.customer_xsd;
